name: socio
description: Social App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  # DateTime
  jiffy: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.4
#   Images
  cached_network_image: ^3.2.0
  image_picker: ^0.7.2+1
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^8.0.5
  geocoding: ^2.0.4
  # Firebase And Notification
  firebase_messaging: ^11.2.7
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.5.3+1
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.11.2
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^4.2.0
  url_launcher: ^6.1.2
  dropdown_search: ^3.0.1
  badges: ^2.0.2
  # Icon
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^5.4.2
  # device_preview: ^0.7.5
  responsive_builder: ^0.4.2
  image_pickers: ^2.0.0+2
  awesome_dialog: ^3.0.2
  modal_progress_hud_nsn: ^0.3.0
  hexcolor: ^3.0.1
  iconly: ^1.0.1
  firebase_storage: ^10.3.11
  fluttertoast: ^8.0.8
  awesome_snackbar_content: ^0.1.0
  flutter_facebook_auth: ^5.0.6
  flutter_custom_selector: ^0.0.3
  flutter_multi_select_items: ^0.4.2
  direct_select_flutter: ^1.1.1
  dropdown_button2: ^1.9.2
  flashy_tab_bar2: ^0.0.5
  floating_frosted_bottom_bar: ^0.0.1
  anim_search_bar: ^2.0.3
  carousel_slider: ^4.2.1
  floating_bottom_navigation_bar: ^1.5.2
  shaky_animated_listview: ^0.0.5
  clippy_flutter: ^1.1.1
  modal_bottom_sheet: ^2.1.2
  shape_of_view_null_safe: ^2.0.0
  flutter_sticky_widgets: ^0.0.3
  emoji_picker_flutter: ^1.5.1
  rflutter_alert: ^2.0.4
  photo_view: ^0.14.0
  material_floating_search_bar: ^0.3.7
  ntp: ^2.0.0
  open_file: ^3.2.1
  image_downloader: ^0.31.0
  gallery_saver: ^2.3.2
  tap_to_expand: ^0.6.1
  dot_navigation_bar:
  status_bar_control: ^3.2.1
  hotreloader: ^3.0.5
  age_calculator: ^1.0.0
  bottom_picker: ^2.0.1
  flutter_phoenix: ^1.1.0
  restart_app: ^1.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf


    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf

  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/images/
#    - assets/lottie/
#
#  fonts:
#    - family: Nunito
#      fonts:
#        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
#        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
